import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import { Navigation } from '@src/components/Navigation'
import SocketProvider from '@src/context/socket-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        <main>
          {children}
        </main>
        <footer>
          
        </footer>
        </body>
    </html>
  )
}
