import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import { Navigation } from '@src/components/Navigation'
import Logo from '@src/components/logo'
import PageProvider from '@src/contexts/blogpost-page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <PageProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navigation/>
          <main>
            {children}
          </main>
          <footer className=''>
            <Logo mode={'footer'} className={'float-left mx-4'}/>
            <div className='w-4 float-right mx-4'></div>
          </footer>
        </body>
      </html>
    </PageProvider>
  )
}
