"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
require("./globals.css");
const google_1 = require("next/font/google");
const react_1 = __importDefault(require("react"));
const Navigation_1 = require("../components/Navigation");
const logo_1 = __importDefault(require("../components/logo"));
const blogpost_page_1 = __importDefault(require("../contexts/blogpost-page"));
const inter = (0, google_1.Inter)({ subsets: ['latin'] });
exports.metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
function RootLayout({ children, }) {
    return (<blogpost_page_1.default>
      <html lang="en">
        <body className={inter.className}>
          <Navigation_1.Navigation />
          <main>{children}</main>
          <footer className="">
            <logo_1.default mode={'footer'} className={'float-left mx-4'}/>
            <div className="w-4 float-right mx-4"></div>
          </footer>
        </body>
      </html>
    </blogpost_page_1.default>);
}
exports.default = RootLayout;
//# sourceMappingURL=layout.jsx.map